/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as XRouteImport } from './routes/x'
import { Route as UsersRouteImport } from './routes/users'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as SystemSettingsRouteImport } from './routes/system-settings'
import { Route as SubscriptionRouteImport } from './routes/subscription'
import { Route as SubscribeFilesRouteImport } from './routes/subscribe-files'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as ProbeRouteImport } from './routes/probe'
import { Route as NodesRouteImport } from './routes/nodes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GeneratorRouteImport } from './routes/generator'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as CustomRulesRouteImport } from './routes/custom-rules'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as IndexRouteImport } from './routes/index'
import { Route as XIndexRouteImport } from './routes/x/index'
import { Route as TemplatesIndexRouteImport } from './routes/templates.index'
import { Route as SubscriptionIndexRouteImport } from './routes/subscription.index'
import { Route as SubscribeFilesIndexRouteImport } from './routes/subscribe-files.index'
import { Route as NodesIndexRouteImport } from './routes/nodes.index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as CustomRulesIndexRouteImport } from './routes/custom-rules.index'
import { Route as XDocsRouteImport } from './routes/x/docs'
import { Route as SubscribeFilesCustomRouteImport } from './routes/subscribe-files.custom'
import { Route as DocsUsersRouteImport } from './routes/docs/users'
import { Route as DocsUpdateRouteImport } from './routes/docs/update'
import { Route as DocsTrafficInfoRouteImport } from './routes/docs/traffic-info'
import { Route as DocsTemplatesV3RouteImport } from './routes/docs/templatesV3'
import { Route as DocsTemplatesRouteImport } from './routes/docs/templates'
import { Route as DocsSystemSettingsRouteImport } from './routes/docs/system-settings'
import { Route as DocsSystemRequirementsRouteImport } from './routes/docs/system-requirements'
import { Route as DocsSubscriptionLinkRouteImport } from './routes/docs/subscription-link'
import { Route as DocsSubscribeFilesRouteImport } from './routes/docs/subscribe-files'
import { Route as DocsSettingsRouteImport } from './routes/docs/settings'
import { Route as DocsQuickStartRouteImport } from './routes/docs/quick-start'
import { Route as DocsProxyProvidersAdvancedRouteImport } from './routes/docs/proxy-providers-advanced'
import { Route as DocsProxyProvidersRouteImport } from './routes/docs/proxy-providers'
import { Route as DocsProbeRouteImport } from './routes/docs/probe'
import { Route as DocsNodesRouteImport } from './routes/docs/nodes'
import { Route as DocsNodeSpeedtestRouteImport } from './routes/docs/node-speedtest'
import { Route as DocsLoginRouteImport } from './routes/docs/login'
import { Route as DocsInstallDockerRouteImport } from './routes/docs/install-docker'
import { Route as DocsInstallDirectRouteImport } from './routes/docs/install-direct'
import { Route as DocsImportSubscriptionRouteImport } from './routes/docs/import-subscription'
import { Route as DocsGeneratorRouteImport } from './routes/docs/generator'
import { Route as DocsFeaturesRouteImport } from './routes/docs/features'
import { Route as DocsFaqRouteImport } from './routes/docs/faq'
import { Route as DocsExternalSubscriptionsRouteImport } from './routes/docs/external-subscriptions'
import { Route as DocsEditNodesRouteImport } from './routes/docs/edit-nodes'
import { Route as DocsCustomRulesRouteImport } from './routes/docs/custom-rules'
import { Route as DocsClientSetupRouteImport } from './routes/docs/client-setup'
import { Route as DocsChainProxyRouteImport } from './routes/docs/chain-proxy'
import { Route as DocsAboutRouteImport } from './routes/docs/about'
import { Route as XDocsIndexRouteImport } from './routes/x/docs/index'
import { Route as XDocsXraySystemConfigRouteImport } from './routes/x/docs/xray-system-config'
import { Route as XDocsXrayServiceRouteImport } from './routes/x/docs/xray-service'
import { Route as XDocsXrayRoutingRouteImport } from './routes/x/docs/xray-routing'
import { Route as XDocsXrayOutboundsRouteImport } from './routes/x/docs/xray-outbounds'
import { Route as XDocsXrayInboundsRouteImport } from './routes/x/docs/xray-inbounds'
import { Route as XDocsUsersRouteImport } from './routes/x/docs/users'
import { Route as XDocsUpgradeFromMmwRouteImport } from './routes/x/docs/upgrade-from-mmw'
import { Route as XDocsUpdateRouteImport } from './routes/x/docs/update'
import { Route as XDocsTutorialRouteImport } from './routes/x/docs/tutorial'
import { Route as XDocsToolMmwxTgbotRouteImport } from './routes/x/docs/tool-mmwx-tgbot'
import { Route as XDocsToolCloudflareTurnstileRouteImport } from './routes/x/docs/tool-cloudflare-turnstile'
import { Route as XDocsTemplatesRouteImport } from './routes/x/docs/templates'
import { Route as XDocsSystemSettingsRouteImport } from './routes/x/docs/system-settings'
import { Route as XDocsSystemRequirementsRouteImport } from './routes/x/docs/system-requirements'
import { Route as XDocsSubscribeFilesRouteImport } from './routes/x/docs/subscribe-files'
import { Route as XDocsShareServerRouteImport } from './routes/x/docs/share-server'
import { Route as XDocsRoutedOutboundRouteImport } from './routes/x/docs/routed-outbound'
import { Route as XDocsRemoteServersRouteImport } from './routes/x/docs/remote-servers'
import { Route as XDocsQuickStartRouteImport } from './routes/x/docs/quick-start'
import { Route as XDocsProtocolVmessRouteImport } from './routes/x/docs/protocol-vmess'
import { Route as XDocsProtocolVlessRouteImport } from './routes/x/docs/protocol-vless'
import { Route as XDocsProtocolTrojanRouteImport } from './routes/x/docs/protocol-trojan'
import { Route as XDocsProtocolShadowsocksRouteImport } from './routes/x/docs/protocol-shadowsocks'
import { Route as XDocsProtocolMatrixRouteImport } from './routes/x/docs/protocol-matrix'
import { Route as XDocsProtocolHysteria2RouteImport } from './routes/x/docs/protocol-hysteria2'
import { Route as XDocsProtocolAnytlsRouteImport } from './routes/x/docs/protocol-anytls'
import { Route as XDocsPackagesRouteImport } from './routes/x/docs/packages'
import { Route as XDocsNodesRouteImport } from './routes/x/docs/nodes'
import { Route as XDocsNodeSpeedtestRouteImport } from './routes/x/docs/node-speedtest'
import { Route as XDocsNodeRatelimitRouteImport } from './routes/x/docs/node-ratelimit'
import { Route as XDocsMcpRouteImport } from './routes/x/docs/mcp'
import { Route as XDocsInstallDockerRouteImport } from './routes/x/docs/install-docker'
import { Route as XDocsInstallDirectRouteImport } from './routes/x/docs/install-direct'
import { Route as XDocsInstallAgentRouteImport } from './routes/x/docs/install-agent'
import { Route as XDocsGeneratorRouteImport } from './routes/x/docs/generator'
import { Route as XDocsFeaturesRouteImport } from './routes/x/docs/features'
import { Route as XDocsFaqRouteImport } from './routes/x/docs/faq'
import { Route as XDocsEmbeddedXrayRouteImport } from './routes/x/docs/embedded-xray'
import { Route as XDocsCustomRulesRouteImport } from './routes/x/docs/custom-rules'
import { Route as XDocsComparisonRouteImport } from './routes/x/docs/comparison'
import { Route as XDocsChangelogRouteImport } from './routes/x/docs/changelog'
import { Route as XDocsCertificatesRouteImport } from './routes/x/docs/certificates'
import { Route as XDocsAboutRouteImport } from './routes/x/docs/about'

const XRoute = XRouteImport.update({
  id: '/x',
  path: '/x',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemSettingsRoute = SystemSettingsRouteImport.update({
  id: '/system-settings',
  path: '/system-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionRoute = SubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscribeFilesRoute = SubscribeFilesRouteImport.update({
  id: '/subscribe-files',
  path: '/subscribe-files',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const ProbeRoute = ProbeRouteImport.update({
  id: '/probe',
  path: '/probe',
  getParentRoute: () => rootRouteImport,
} as any)
const NodesRoute = NodesRouteImport.update({
  id: '/nodes',
  path: '/nodes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GeneratorRoute = GeneratorRouteImport.update({
  id: '/generator',
  path: '/generator',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomRulesRoute = CustomRulesRouteImport.update({
  id: '/custom-rules',
  path: '/custom-rules',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const XIndexRoute = XIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => XRoute,
} as any)
const TemplatesIndexRoute = TemplatesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TemplatesRoute,
} as any)
const SubscriptionIndexRoute = SubscriptionIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SubscriptionRoute,
} as any)
const SubscribeFilesIndexRoute = SubscribeFilesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SubscribeFilesRoute,
} as any)
const NodesIndexRoute = NodesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NodesRoute,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const CustomRulesIndexRoute = CustomRulesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CustomRulesRoute,
} as any)
const XDocsRoute = XDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => XRoute,
} as any)
const SubscribeFilesCustomRoute = SubscribeFilesCustomRouteImport.update({
  id: '/custom',
  path: '/custom',
  getParentRoute: () => SubscribeFilesRoute,
} as any)
const DocsUsersRoute = DocsUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DocsRoute,
} as any)
const DocsUpdateRoute = DocsUpdateRouteImport.update({
  id: '/update',
  path: '/update',
  getParentRoute: () => DocsRoute,
} as any)
const DocsTrafficInfoRoute = DocsTrafficInfoRouteImport.update({
  id: '/traffic-info',
  path: '/traffic-info',
  getParentRoute: () => DocsRoute,
} as any)
const DocsTemplatesV3Route = DocsTemplatesV3RouteImport.update({
  id: '/templatesV3',
  path: '/templatesV3',
  getParentRoute: () => DocsRoute,
} as any)
const DocsTemplatesRoute = DocsTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => DocsRoute,
} as any)
const DocsSystemSettingsRoute = DocsSystemSettingsRouteImport.update({
  id: '/system-settings',
  path: '/system-settings',
  getParentRoute: () => DocsRoute,
} as any)
const DocsSystemRequirementsRoute = DocsSystemRequirementsRouteImport.update({
  id: '/system-requirements',
  path: '/system-requirements',
  getParentRoute: () => DocsRoute,
} as any)
const DocsSubscriptionLinkRoute = DocsSubscriptionLinkRouteImport.update({
  id: '/subscription-link',
  path: '/subscription-link',
  getParentRoute: () => DocsRoute,
} as any)
const DocsSubscribeFilesRoute = DocsSubscribeFilesRouteImport.update({
  id: '/subscribe-files',
  path: '/subscribe-files',
  getParentRoute: () => DocsRoute,
} as any)
const DocsSettingsRoute = DocsSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DocsRoute,
} as any)
const DocsQuickStartRoute = DocsQuickStartRouteImport.update({
  id: '/quick-start',
  path: '/quick-start',
  getParentRoute: () => DocsRoute,
} as any)
const DocsProxyProvidersAdvancedRoute =
  DocsProxyProvidersAdvancedRouteImport.update({
    id: '/proxy-providers-advanced',
    path: '/proxy-providers-advanced',
    getParentRoute: () => DocsRoute,
  } as any)
const DocsProxyProvidersRoute = DocsProxyProvidersRouteImport.update({
  id: '/proxy-providers',
  path: '/proxy-providers',
  getParentRoute: () => DocsRoute,
} as any)
const DocsProbeRoute = DocsProbeRouteImport.update({
  id: '/probe',
  path: '/probe',
  getParentRoute: () => DocsRoute,
} as any)
const DocsNodesRoute = DocsNodesRouteImport.update({
  id: '/nodes',
  path: '/nodes',
  getParentRoute: () => DocsRoute,
} as any)
const DocsNodeSpeedtestRoute = DocsNodeSpeedtestRouteImport.update({
  id: '/node-speedtest',
  path: '/node-speedtest',
  getParentRoute: () => DocsRoute,
} as any)
const DocsLoginRoute = DocsLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => DocsRoute,
} as any)
const DocsInstallDockerRoute = DocsInstallDockerRouteImport.update({
  id: '/install-docker',
  path: '/install-docker',
  getParentRoute: () => DocsRoute,
} as any)
const DocsInstallDirectRoute = DocsInstallDirectRouteImport.update({
  id: '/install-direct',
  path: '/install-direct',
  getParentRoute: () => DocsRoute,
} as any)
const DocsImportSubscriptionRoute = DocsImportSubscriptionRouteImport.update({
  id: '/import-subscription',
  path: '/import-subscription',
  getParentRoute: () => DocsRoute,
} as any)
const DocsGeneratorRoute = DocsGeneratorRouteImport.update({
  id: '/generator',
  path: '/generator',
  getParentRoute: () => DocsRoute,
} as any)
const DocsFeaturesRoute = DocsFeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => DocsRoute,
} as any)
const DocsFaqRoute = DocsFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => DocsRoute,
} as any)
const DocsExternalSubscriptionsRoute =
  DocsExternalSubscriptionsRouteImport.update({
    id: '/external-subscriptions',
    path: '/external-subscriptions',
    getParentRoute: () => DocsRoute,
  } as any)
const DocsEditNodesRoute = DocsEditNodesRouteImport.update({
  id: '/edit-nodes',
  path: '/edit-nodes',
  getParentRoute: () => DocsRoute,
} as any)
const DocsCustomRulesRoute = DocsCustomRulesRouteImport.update({
  id: '/custom-rules',
  path: '/custom-rules',
  getParentRoute: () => DocsRoute,
} as any)
const DocsClientSetupRoute = DocsClientSetupRouteImport.update({
  id: '/client-setup',
  path: '/client-setup',
  getParentRoute: () => DocsRoute,
} as any)
const DocsChainProxyRoute = DocsChainProxyRouteImport.update({
  id: '/chain-proxy',
  path: '/chain-proxy',
  getParentRoute: () => DocsRoute,
} as any)
const DocsAboutRoute = DocsAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => DocsRoute,
} as any)
const XDocsIndexRoute = XDocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => XDocsRoute,
} as any)
const XDocsXraySystemConfigRoute = XDocsXraySystemConfigRouteImport.update({
  id: '/xray-system-config',
  path: '/xray-system-config',
  getParentRoute: () => XDocsRoute,
} as any)
const XDocsXrayServiceRoute = XDocsXrayServiceRouteImport.update({
  id: '/xray-service',
  path: '/xray-service',
  getParentRoute: () => XDocsRoute,
} as any)
const XDocsXrayRoutingRoute = XDocsXrayRoutingRouteImport.update({
  id: '/xray-routing',
  path: '/xray-routing',
  getParentRoute: () => XDocsRoute,
} as any)
const XDocsXrayOutboundsRoute = XDocsXrayOutboundsRouteImport.update({
  id: '/xray-outbounds',
  path: '/xray-outbounds',
  getParentRoute: () => XDocsRoute,
} as any)
const XDocsXrayInboundsRoute = XDocsXrayInboundsRouteImport.update({
  id: '/xray-inbounds',
  path: '/xray-inbounds',
  getParentRoute: () => XDocsRoute,
} as any)
const XDocsUsersRoute = XDocsUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => XDocsRoute,
} as any)
const XDocsUpgradeFromMmwRoute = XDocsUpgradeFromMmwRouteImport.update({
  id: '/upgrade-from-mmw',
  path: '/upgrade-from-mmw',
  getParentRoute: () => XDocsRoute,
} as any)
const XDocsUpdateRoute = XDocsUpdateRouteImport.update({
  id: '/update',
  path: '/update',
  getParentRoute: () => XDocsRoute,
} as any)
const XDocsTutorialRoute = XDocsTutorialRouteImport.update({
  id: '/tutorial',
  path: '/tutorial',
  getParentRoute: () => XDocsRoute,
} as any)
const XDocsToolMmwxTgbotRoute = XDocsToolMmwxTgbotRouteImport.update({
  id: '/tool-mmwx-tgbot',
  path: '/tool-mmwx-tgbot',
  getParentRoute: () => XDocsRoute,
} as any)
const XDocsToolCloudflareTurnstileRoute =
  XDocsToolCloudflareTurnstileRouteImport.update({
    id: '/tool-cloudflare-turnstile',
    path: '/tool-cloudflare-turnstile',
    getParentRoute: () => XDocsRoute,
  } as any)
const XDocsTemplatesRoute = XDocsTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => XDocsRoute,
} as any)
const XDocsSystemSettingsRoute = XDocsSystemSettingsRouteImport.update({
  id: '/system-settings',
  path: '/system-settings',
  getParentRoute: () => XDocsRoute,
} as any)
const XDocsSystemRequirementsRoute = XDocsSystemRequirementsRouteImport.update({
  id: '/system-requirements',
  path: '/system-requirements',
  getParentRoute: () => XDocsRoute,
} as any)
const XDocsSubscribeFilesRoute = XDocsSubscribeFilesRouteImport.update({
  id: '/subscribe-files',
  path: '/subscribe-files',
  getParentRoute: () => XDocsRoute,
} as any)
const XDocsShareServerRoute = XDocsShareServerRouteImport.update({
  id: '/share-server',
  path: '/share-server',
  getParentRoute: () => XDocsRoute,
} as any)
const XDocsRoutedOutboundRoute = XDocsRoutedOutboundRouteImport.update({
  id: '/routed-outbound',
  path: '/routed-outbound',
  getParentRoute: () => XDocsRoute,
} as any)
const XDocsRemoteServersRoute = XDocsRemoteServersRouteImport.update({
  id: '/remote-servers',
  path: '/remote-servers',
  getParentRoute: () => XDocsRoute,
} as any)
const XDocsQuickStartRoute = XDocsQuickStartRouteImport.update({
  id: '/quick-start',
  path: '/quick-start',
  getParentRoute: () => XDocsRoute,
} as any)
const XDocsProtocolVmessRoute = XDocsProtocolVmessRouteImport.update({
  id: '/protocol-vmess',
  path: '/protocol-vmess',
  getParentRoute: () => XDocsRoute,
} as any)
const XDocsProtocolVlessRoute = XDocsProtocolVlessRouteImport.update({
  id: '/protocol-vless',
  path: '/protocol-vless',
  getParentRoute: () => XDocsRoute,
} as any)
const XDocsProtocolTrojanRoute = XDocsProtocolTrojanRouteImport.update({
  id: '/protocol-trojan',
  path: '/protocol-trojan',
  getParentRoute: () => XDocsRoute,
} as any)
const XDocsProtocolShadowsocksRoute =
  XDocsProtocolShadowsocksRouteImport.update({
    id: '/protocol-shadowsocks',
    path: '/protocol-shadowsocks',
    getParentRoute: () => XDocsRoute,
  } as any)
const XDocsProtocolMatrixRoute = XDocsProtocolMatrixRouteImport.update({
  id: '/protocol-matrix',
  path: '/protocol-matrix',
  getParentRoute: () => XDocsRoute,
} as any)
const XDocsProtocolHysteria2Route = XDocsProtocolHysteria2RouteImport.update({
  id: '/protocol-hysteria2',
  path: '/protocol-hysteria2',
  getParentRoute: () => XDocsRoute,
} as any)
const XDocsProtocolAnytlsRoute = XDocsProtocolAnytlsRouteImport.update({
  id: '/protocol-anytls',
  path: '/protocol-anytls',
  getParentRoute: () => XDocsRoute,
} as any)
const XDocsPackagesRoute = XDocsPackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => XDocsRoute,
} as any)
const XDocsNodesRoute = XDocsNodesRouteImport.update({
  id: '/nodes',
  path: '/nodes',
  getParentRoute: () => XDocsRoute,
} as any)
const XDocsNodeSpeedtestRoute = XDocsNodeSpeedtestRouteImport.update({
  id: '/node-speedtest',
  path: '/node-speedtest',
  getParentRoute: () => XDocsRoute,
} as any)
const XDocsNodeRatelimitRoute = XDocsNodeRatelimitRouteImport.update({
  id: '/node-ratelimit',
  path: '/node-ratelimit',
  getParentRoute: () => XDocsRoute,
} as any)
const XDocsMcpRoute = XDocsMcpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => XDocsRoute,
} as any)
const XDocsInstallDockerRoute = XDocsInstallDockerRouteImport.update({
  id: '/install-docker',
  path: '/install-docker',
  getParentRoute: () => XDocsRoute,
} as any)
const XDocsInstallDirectRoute = XDocsInstallDirectRouteImport.update({
  id: '/install-direct',
  path: '/install-direct',
  getParentRoute: () => XDocsRoute,
} as any)
const XDocsInstallAgentRoute = XDocsInstallAgentRouteImport.update({
  id: '/install-agent',
  path: '/install-agent',
  getParentRoute: () => XDocsRoute,
} as any)
const XDocsGeneratorRoute = XDocsGeneratorRouteImport.update({
  id: '/generator',
  path: '/generator',
  getParentRoute: () => XDocsRoute,
} as any)
const XDocsFeaturesRoute = XDocsFeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => XDocsRoute,
} as any)
const XDocsFaqRoute = XDocsFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => XDocsRoute,
} as any)
const XDocsEmbeddedXrayRoute = XDocsEmbeddedXrayRouteImport.update({
  id: '/embedded-xray',
  path: '/embedded-xray',
  getParentRoute: () => XDocsRoute,
} as any)
const XDocsCustomRulesRoute = XDocsCustomRulesRouteImport.update({
  id: '/custom-rules',
  path: '/custom-rules',
  getParentRoute: () => XDocsRoute,
} as any)
const XDocsComparisonRoute = XDocsComparisonRouteImport.update({
  id: '/comparison',
  path: '/comparison',
  getParentRoute: () => XDocsRoute,
} as any)
const XDocsChangelogRoute = XDocsChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => XDocsRoute,
} as any)
const XDocsCertificatesRoute = XDocsCertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => XDocsRoute,
} as any)
const XDocsAboutRoute = XDocsAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => XDocsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/changelog': typeof ChangelogRoute
  '/custom-rules': typeof CustomRulesRouteWithChildren
  '/docs': typeof DocsRouteWithChildren
  '/generator': typeof GeneratorRoute
  '/login': typeof LoginRoute
  '/nodes': typeof NodesRouteWithChildren
  '/probe': typeof ProbeRoute
  '/rules': typeof RulesRoute
  '/settings': typeof SettingsRoute
  '/subscribe-files': typeof SubscribeFilesRouteWithChildren
  '/subscription': typeof SubscriptionRouteWithChildren
  '/system-settings': typeof SystemSettingsRoute
  '/templates': typeof TemplatesRouteWithChildren
  '/users': typeof UsersRoute
  '/x': typeof XRouteWithChildren
  '/docs/about': typeof DocsAboutRoute
  '/docs/chain-proxy': typeof DocsChainProxyRoute
  '/docs/client-setup': typeof DocsClientSetupRoute
  '/docs/custom-rules': typeof DocsCustomRulesRoute
  '/docs/edit-nodes': typeof DocsEditNodesRoute
  '/docs/external-subscriptions': typeof DocsExternalSubscriptionsRoute
  '/docs/faq': typeof DocsFaqRoute
  '/docs/features': typeof DocsFeaturesRoute
  '/docs/generator': typeof DocsGeneratorRoute
  '/docs/import-subscription': typeof DocsImportSubscriptionRoute
  '/docs/install-direct': typeof DocsInstallDirectRoute
  '/docs/install-docker': typeof DocsInstallDockerRoute
  '/docs/login': typeof DocsLoginRoute
  '/docs/node-speedtest': typeof DocsNodeSpeedtestRoute
  '/docs/nodes': typeof DocsNodesRoute
  '/docs/probe': typeof DocsProbeRoute
  '/docs/proxy-providers': typeof DocsProxyProvidersRoute
  '/docs/proxy-providers-advanced': typeof DocsProxyProvidersAdvancedRoute
  '/docs/quick-start': typeof DocsQuickStartRoute
  '/docs/settings': typeof DocsSettingsRoute
  '/docs/subscribe-files': typeof DocsSubscribeFilesRoute
  '/docs/subscription-link': typeof DocsSubscriptionLinkRoute
  '/docs/system-requirements': typeof DocsSystemRequirementsRoute
  '/docs/system-settings': typeof DocsSystemSettingsRoute
  '/docs/templates': typeof DocsTemplatesRoute
  '/docs/templatesV3': typeof DocsTemplatesV3Route
  '/docs/traffic-info': typeof DocsTrafficInfoRoute
  '/docs/update': typeof DocsUpdateRoute
  '/docs/users': typeof DocsUsersRoute
  '/subscribe-files/custom': typeof SubscribeFilesCustomRoute
  '/x/docs': typeof XDocsRouteWithChildren
  '/custom-rules/': typeof CustomRulesIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/nodes/': typeof NodesIndexRoute
  '/subscribe-files/': typeof SubscribeFilesIndexRoute
  '/subscription/': typeof SubscriptionIndexRoute
  '/templates/': typeof TemplatesIndexRoute
  '/x/': typeof XIndexRoute
  '/x/docs/about': typeof XDocsAboutRoute
  '/x/docs/certificates': typeof XDocsCertificatesRoute
  '/x/docs/changelog': typeof XDocsChangelogRoute
  '/x/docs/comparison': typeof XDocsComparisonRoute
  '/x/docs/custom-rules': typeof XDocsCustomRulesRoute
  '/x/docs/embedded-xray': typeof XDocsEmbeddedXrayRoute
  '/x/docs/faq': typeof XDocsFaqRoute
  '/x/docs/features': typeof XDocsFeaturesRoute
  '/x/docs/generator': typeof XDocsGeneratorRoute
  '/x/docs/install-agent': typeof XDocsInstallAgentRoute
  '/x/docs/install-direct': typeof XDocsInstallDirectRoute
  '/x/docs/install-docker': typeof XDocsInstallDockerRoute
  '/x/docs/mcp': typeof XDocsMcpRoute
  '/x/docs/node-ratelimit': typeof XDocsNodeRatelimitRoute
  '/x/docs/node-speedtest': typeof XDocsNodeSpeedtestRoute
  '/x/docs/nodes': typeof XDocsNodesRoute
  '/x/docs/packages': typeof XDocsPackagesRoute
  '/x/docs/protocol-anytls': typeof XDocsProtocolAnytlsRoute
  '/x/docs/protocol-hysteria2': typeof XDocsProtocolHysteria2Route
  '/x/docs/protocol-matrix': typeof XDocsProtocolMatrixRoute
  '/x/docs/protocol-shadowsocks': typeof XDocsProtocolShadowsocksRoute
  '/x/docs/protocol-trojan': typeof XDocsProtocolTrojanRoute
  '/x/docs/protocol-vless': typeof XDocsProtocolVlessRoute
  '/x/docs/protocol-vmess': typeof XDocsProtocolVmessRoute
  '/x/docs/quick-start': typeof XDocsQuickStartRoute
  '/x/docs/remote-servers': typeof XDocsRemoteServersRoute
  '/x/docs/routed-outbound': typeof XDocsRoutedOutboundRoute
  '/x/docs/share-server': typeof XDocsShareServerRoute
  '/x/docs/subscribe-files': typeof XDocsSubscribeFilesRoute
  '/x/docs/system-requirements': typeof XDocsSystemRequirementsRoute
  '/x/docs/system-settings': typeof XDocsSystemSettingsRoute
  '/x/docs/templates': typeof XDocsTemplatesRoute
  '/x/docs/tool-cloudflare-turnstile': typeof XDocsToolCloudflareTurnstileRoute
  '/x/docs/tool-mmwx-tgbot': typeof XDocsToolMmwxTgbotRoute
  '/x/docs/tutorial': typeof XDocsTutorialRoute
  '/x/docs/update': typeof XDocsUpdateRoute
  '/x/docs/upgrade-from-mmw': typeof XDocsUpgradeFromMmwRoute
  '/x/docs/users': typeof XDocsUsersRoute
  '/x/docs/xray-inbounds': typeof XDocsXrayInboundsRoute
  '/x/docs/xray-outbounds': typeof XDocsXrayOutboundsRoute
  '/x/docs/xray-routing': typeof XDocsXrayRoutingRoute
  '/x/docs/xray-service': typeof XDocsXrayServiceRoute
  '/x/docs/xray-system-config': typeof XDocsXraySystemConfigRoute
  '/x/docs/': typeof XDocsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/changelog': typeof ChangelogRoute
  '/generator': typeof GeneratorRoute
  '/login': typeof LoginRoute
  '/probe': typeof ProbeRoute
  '/rules': typeof RulesRoute
  '/settings': typeof SettingsRoute
  '/system-settings': typeof SystemSettingsRoute
  '/users': typeof UsersRoute
  '/docs/about': typeof DocsAboutRoute
  '/docs/chain-proxy': typeof DocsChainProxyRoute
  '/docs/client-setup': typeof DocsClientSetupRoute
  '/docs/custom-rules': typeof DocsCustomRulesRoute
  '/docs/edit-nodes': typeof DocsEditNodesRoute
  '/docs/external-subscriptions': typeof DocsExternalSubscriptionsRoute
  '/docs/faq': typeof DocsFaqRoute
  '/docs/features': typeof DocsFeaturesRoute
  '/docs/generator': typeof DocsGeneratorRoute
  '/docs/import-subscription': typeof DocsImportSubscriptionRoute
  '/docs/install-direct': typeof DocsInstallDirectRoute
  '/docs/install-docker': typeof DocsInstallDockerRoute
  '/docs/login': typeof DocsLoginRoute
  '/docs/node-speedtest': typeof DocsNodeSpeedtestRoute
  '/docs/nodes': typeof DocsNodesRoute
  '/docs/probe': typeof DocsProbeRoute
  '/docs/proxy-providers': typeof DocsProxyProvidersRoute
  '/docs/proxy-providers-advanced': typeof DocsProxyProvidersAdvancedRoute
  '/docs/quick-start': typeof DocsQuickStartRoute
  '/docs/settings': typeof DocsSettingsRoute
  '/docs/subscribe-files': typeof DocsSubscribeFilesRoute
  '/docs/subscription-link': typeof DocsSubscriptionLinkRoute
  '/docs/system-requirements': typeof DocsSystemRequirementsRoute
  '/docs/system-settings': typeof DocsSystemSettingsRoute
  '/docs/templates': typeof DocsTemplatesRoute
  '/docs/templatesV3': typeof DocsTemplatesV3Route
  '/docs/traffic-info': typeof DocsTrafficInfoRoute
  '/docs/update': typeof DocsUpdateRoute
  '/docs/users': typeof DocsUsersRoute
  '/subscribe-files/custom': typeof SubscribeFilesCustomRoute
  '/custom-rules': typeof CustomRulesIndexRoute
  '/docs': typeof DocsIndexRoute
  '/nodes': typeof NodesIndexRoute
  '/subscribe-files': typeof SubscribeFilesIndexRoute
  '/subscription': typeof SubscriptionIndexRoute
  '/templates': typeof TemplatesIndexRoute
  '/x': typeof XIndexRoute
  '/x/docs/about': typeof XDocsAboutRoute
  '/x/docs/certificates': typeof XDocsCertificatesRoute
  '/x/docs/changelog': typeof XDocsChangelogRoute
  '/x/docs/comparison': typeof XDocsComparisonRoute
  '/x/docs/custom-rules': typeof XDocsCustomRulesRoute
  '/x/docs/embedded-xray': typeof XDocsEmbeddedXrayRoute
  '/x/docs/faq': typeof XDocsFaqRoute
  '/x/docs/features': typeof XDocsFeaturesRoute
  '/x/docs/generator': typeof XDocsGeneratorRoute
  '/x/docs/install-agent': typeof XDocsInstallAgentRoute
  '/x/docs/install-direct': typeof XDocsInstallDirectRoute
  '/x/docs/install-docker': typeof XDocsInstallDockerRoute
  '/x/docs/mcp': typeof XDocsMcpRoute
  '/x/docs/node-ratelimit': typeof XDocsNodeRatelimitRoute
  '/x/docs/node-speedtest': typeof XDocsNodeSpeedtestRoute
  '/x/docs/nodes': typeof XDocsNodesRoute
  '/x/docs/packages': typeof XDocsPackagesRoute
  '/x/docs/protocol-anytls': typeof XDocsProtocolAnytlsRoute
  '/x/docs/protocol-hysteria2': typeof XDocsProtocolHysteria2Route
  '/x/docs/protocol-matrix': typeof XDocsProtocolMatrixRoute
  '/x/docs/protocol-shadowsocks': typeof XDocsProtocolShadowsocksRoute
  '/x/docs/protocol-trojan': typeof XDocsProtocolTrojanRoute
  '/x/docs/protocol-vless': typeof XDocsProtocolVlessRoute
  '/x/docs/protocol-vmess': typeof XDocsProtocolVmessRoute
  '/x/docs/quick-start': typeof XDocsQuickStartRoute
  '/x/docs/remote-servers': typeof XDocsRemoteServersRoute
  '/x/docs/routed-outbound': typeof XDocsRoutedOutboundRoute
  '/x/docs/share-server': typeof XDocsShareServerRoute
  '/x/docs/subscribe-files': typeof XDocsSubscribeFilesRoute
  '/x/docs/system-requirements': typeof XDocsSystemRequirementsRoute
  '/x/docs/system-settings': typeof XDocsSystemSettingsRoute
  '/x/docs/templates': typeof XDocsTemplatesRoute
  '/x/docs/tool-cloudflare-turnstile': typeof XDocsToolCloudflareTurnstileRoute
  '/x/docs/tool-mmwx-tgbot': typeof XDocsToolMmwxTgbotRoute
  '/x/docs/tutorial': typeof XDocsTutorialRoute
  '/x/docs/update': typeof XDocsUpdateRoute
  '/x/docs/upgrade-from-mmw': typeof XDocsUpgradeFromMmwRoute
  '/x/docs/users': typeof XDocsUsersRoute
  '/x/docs/xray-inbounds': typeof XDocsXrayInboundsRoute
  '/x/docs/xray-outbounds': typeof XDocsXrayOutboundsRoute
  '/x/docs/xray-routing': typeof XDocsXrayRoutingRoute
  '/x/docs/xray-service': typeof XDocsXrayServiceRoute
  '/x/docs/xray-system-config': typeof XDocsXraySystemConfigRoute
  '/x/docs': typeof XDocsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/changelog': typeof ChangelogRoute
  '/custom-rules': typeof CustomRulesRouteWithChildren
  '/docs': typeof DocsRouteWithChildren
  '/generator': typeof GeneratorRoute
  '/login': typeof LoginRoute
  '/nodes': typeof NodesRouteWithChildren
  '/probe': typeof ProbeRoute
  '/rules': typeof RulesRoute
  '/settings': typeof SettingsRoute
  '/subscribe-files': typeof SubscribeFilesRouteWithChildren
  '/subscription': typeof SubscriptionRouteWithChildren
  '/system-settings': typeof SystemSettingsRoute
  '/templates': typeof TemplatesRouteWithChildren
  '/users': typeof UsersRoute
  '/x': typeof XRouteWithChildren
  '/docs/about': typeof DocsAboutRoute
  '/docs/chain-proxy': typeof DocsChainProxyRoute
  '/docs/client-setup': typeof DocsClientSetupRoute
  '/docs/custom-rules': typeof DocsCustomRulesRoute
  '/docs/edit-nodes': typeof DocsEditNodesRoute
  '/docs/external-subscriptions': typeof DocsExternalSubscriptionsRoute
  '/docs/faq': typeof DocsFaqRoute
  '/docs/features': typeof DocsFeaturesRoute
  '/docs/generator': typeof DocsGeneratorRoute
  '/docs/import-subscription': typeof DocsImportSubscriptionRoute
  '/docs/install-direct': typeof DocsInstallDirectRoute
  '/docs/install-docker': typeof DocsInstallDockerRoute
  '/docs/login': typeof DocsLoginRoute
  '/docs/node-speedtest': typeof DocsNodeSpeedtestRoute
  '/docs/nodes': typeof DocsNodesRoute
  '/docs/probe': typeof DocsProbeRoute
  '/docs/proxy-providers': typeof DocsProxyProvidersRoute
  '/docs/proxy-providers-advanced': typeof DocsProxyProvidersAdvancedRoute
  '/docs/quick-start': typeof DocsQuickStartRoute
  '/docs/settings': typeof DocsSettingsRoute
  '/docs/subscribe-files': typeof DocsSubscribeFilesRoute
  '/docs/subscription-link': typeof DocsSubscriptionLinkRoute
  '/docs/system-requirements': typeof DocsSystemRequirementsRoute
  '/docs/system-settings': typeof DocsSystemSettingsRoute
  '/docs/templates': typeof DocsTemplatesRoute
  '/docs/templatesV3': typeof DocsTemplatesV3Route
  '/docs/traffic-info': typeof DocsTrafficInfoRoute
  '/docs/update': typeof DocsUpdateRoute
  '/docs/users': typeof DocsUsersRoute
  '/subscribe-files/custom': typeof SubscribeFilesCustomRoute
  '/x/docs': typeof XDocsRouteWithChildren
  '/custom-rules/': typeof CustomRulesIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/nodes/': typeof NodesIndexRoute
  '/subscribe-files/': typeof SubscribeFilesIndexRoute
  '/subscription/': typeof SubscriptionIndexRoute
  '/templates/': typeof TemplatesIndexRoute
  '/x/': typeof XIndexRoute
  '/x/docs/about': typeof XDocsAboutRoute
  '/x/docs/certificates': typeof XDocsCertificatesRoute
  '/x/docs/changelog': typeof XDocsChangelogRoute
  '/x/docs/comparison': typeof XDocsComparisonRoute
  '/x/docs/custom-rules': typeof XDocsCustomRulesRoute
  '/x/docs/embedded-xray': typeof XDocsEmbeddedXrayRoute
  '/x/docs/faq': typeof XDocsFaqRoute
  '/x/docs/features': typeof XDocsFeaturesRoute
  '/x/docs/generator': typeof XDocsGeneratorRoute
  '/x/docs/install-agent': typeof XDocsInstallAgentRoute
  '/x/docs/install-direct': typeof XDocsInstallDirectRoute
  '/x/docs/install-docker': typeof XDocsInstallDockerRoute
  '/x/docs/mcp': typeof XDocsMcpRoute
  '/x/docs/node-ratelimit': typeof XDocsNodeRatelimitRoute
  '/x/docs/node-speedtest': typeof XDocsNodeSpeedtestRoute
  '/x/docs/nodes': typeof XDocsNodesRoute
  '/x/docs/packages': typeof XDocsPackagesRoute
  '/x/docs/protocol-anytls': typeof XDocsProtocolAnytlsRoute
  '/x/docs/protocol-hysteria2': typeof XDocsProtocolHysteria2Route
  '/x/docs/protocol-matrix': typeof XDocsProtocolMatrixRoute
  '/x/docs/protocol-shadowsocks': typeof XDocsProtocolShadowsocksRoute
  '/x/docs/protocol-trojan': typeof XDocsProtocolTrojanRoute
  '/x/docs/protocol-vless': typeof XDocsProtocolVlessRoute
  '/x/docs/protocol-vmess': typeof XDocsProtocolVmessRoute
  '/x/docs/quick-start': typeof XDocsQuickStartRoute
  '/x/docs/remote-servers': typeof XDocsRemoteServersRoute
  '/x/docs/routed-outbound': typeof XDocsRoutedOutboundRoute
  '/x/docs/share-server': typeof XDocsShareServerRoute
  '/x/docs/subscribe-files': typeof XDocsSubscribeFilesRoute
  '/x/docs/system-requirements': typeof XDocsSystemRequirementsRoute
  '/x/docs/system-settings': typeof XDocsSystemSettingsRoute
  '/x/docs/templates': typeof XDocsTemplatesRoute
  '/x/docs/tool-cloudflare-turnstile': typeof XDocsToolCloudflareTurnstileRoute
  '/x/docs/tool-mmwx-tgbot': typeof XDocsToolMmwxTgbotRoute
  '/x/docs/tutorial': typeof XDocsTutorialRoute
  '/x/docs/update': typeof XDocsUpdateRoute
  '/x/docs/upgrade-from-mmw': typeof XDocsUpgradeFromMmwRoute
  '/x/docs/users': typeof XDocsUsersRoute
  '/x/docs/xray-inbounds': typeof XDocsXrayInboundsRoute
  '/x/docs/xray-outbounds': typeof XDocsXrayOutboundsRoute
  '/x/docs/xray-routing': typeof XDocsXrayRoutingRoute
  '/x/docs/xray-service': typeof XDocsXrayServiceRoute
  '/x/docs/xray-system-config': typeof XDocsXraySystemConfigRoute
  '/x/docs/': typeof XDocsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/change-password'
    | '/changelog'
    | '/custom-rules'
    | '/docs'
    | '/generator'
    | '/login'
    | '/nodes'
    | '/probe'
    | '/rules'
    | '/settings'
    | '/subscribe-files'
    | '/subscription'
    | '/system-settings'
    | '/templates'
    | '/users'
    | '/x'
    | '/docs/about'
    | '/docs/chain-proxy'
    | '/docs/client-setup'
    | '/docs/custom-rules'
    | '/docs/edit-nodes'
    | '/docs/external-subscriptions'
    | '/docs/faq'
    | '/docs/features'
    | '/docs/generator'
    | '/docs/import-subscription'
    | '/docs/install-direct'
    | '/docs/install-docker'
    | '/docs/login'
    | '/docs/node-speedtest'
    | '/docs/nodes'
    | '/docs/probe'
    | '/docs/proxy-providers'
    | '/docs/proxy-providers-advanced'
    | '/docs/quick-start'
    | '/docs/settings'
    | '/docs/subscribe-files'
    | '/docs/subscription-link'
    | '/docs/system-requirements'
    | '/docs/system-settings'
    | '/docs/templates'
    | '/docs/templatesV3'
    | '/docs/traffic-info'
    | '/docs/update'
    | '/docs/users'
    | '/subscribe-files/custom'
    | '/x/docs'
    | '/custom-rules/'
    | '/docs/'
    | '/nodes/'
    | '/subscribe-files/'
    | '/subscription/'
    | '/templates/'
    | '/x/'
    | '/x/docs/about'
    | '/x/docs/certificates'
    | '/x/docs/changelog'
    | '/x/docs/comparison'
    | '/x/docs/custom-rules'
    | '/x/docs/embedded-xray'
    | '/x/docs/faq'
    | '/x/docs/features'
    | '/x/docs/generator'
    | '/x/docs/install-agent'
    | '/x/docs/install-direct'
    | '/x/docs/install-docker'
    | '/x/docs/mcp'
    | '/x/docs/node-ratelimit'
    | '/x/docs/node-speedtest'
    | '/x/docs/nodes'
    | '/x/docs/packages'
    | '/x/docs/protocol-anytls'
    | '/x/docs/protocol-hysteria2'
    | '/x/docs/protocol-matrix'
    | '/x/docs/protocol-shadowsocks'
    | '/x/docs/protocol-trojan'
    | '/x/docs/protocol-vless'
    | '/x/docs/protocol-vmess'
    | '/x/docs/quick-start'
    | '/x/docs/remote-servers'
    | '/x/docs/routed-outbound'
    | '/x/docs/share-server'
    | '/x/docs/subscribe-files'
    | '/x/docs/system-requirements'
    | '/x/docs/system-settings'
    | '/x/docs/templates'
    | '/x/docs/tool-cloudflare-turnstile'
    | '/x/docs/tool-mmwx-tgbot'
    | '/x/docs/tutorial'
    | '/x/docs/update'
    | '/x/docs/upgrade-from-mmw'
    | '/x/docs/users'
    | '/x/docs/xray-inbounds'
    | '/x/docs/xray-outbounds'
    | '/x/docs/xray-routing'
    | '/x/docs/xray-service'
    | '/x/docs/xray-system-config'
    | '/x/docs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/change-password'
    | '/changelog'
    | '/generator'
    | '/login'
    | '/probe'
    | '/rules'
    | '/settings'
    | '/system-settings'
    | '/users'
    | '/docs/about'
    | '/docs/chain-proxy'
    | '/docs/client-setup'
    | '/docs/custom-rules'
    | '/docs/edit-nodes'
    | '/docs/external-subscriptions'
    | '/docs/faq'
    | '/docs/features'
    | '/docs/generator'
    | '/docs/import-subscription'
    | '/docs/install-direct'
    | '/docs/install-docker'
    | '/docs/login'
    | '/docs/node-speedtest'
    | '/docs/nodes'
    | '/docs/probe'
    | '/docs/proxy-providers'
    | '/docs/proxy-providers-advanced'
    | '/docs/quick-start'
    | '/docs/settings'
    | '/docs/subscribe-files'
    | '/docs/subscription-link'
    | '/docs/system-requirements'
    | '/docs/system-settings'
    | '/docs/templates'
    | '/docs/templatesV3'
    | '/docs/traffic-info'
    | '/docs/update'
    | '/docs/users'
    | '/subscribe-files/custom'
    | '/custom-rules'
    | '/docs'
    | '/nodes'
    | '/subscribe-files'
    | '/subscription'
    | '/templates'
    | '/x'
    | '/x/docs/about'
    | '/x/docs/certificates'
    | '/x/docs/changelog'
    | '/x/docs/comparison'
    | '/x/docs/custom-rules'
    | '/x/docs/embedded-xray'
    | '/x/docs/faq'
    | '/x/docs/features'
    | '/x/docs/generator'
    | '/x/docs/install-agent'
    | '/x/docs/install-direct'
    | '/x/docs/install-docker'
    | '/x/docs/mcp'
    | '/x/docs/node-ratelimit'
    | '/x/docs/node-speedtest'
    | '/x/docs/nodes'
    | '/x/docs/packages'
    | '/x/docs/protocol-anytls'
    | '/x/docs/protocol-hysteria2'
    | '/x/docs/protocol-matrix'
    | '/x/docs/protocol-shadowsocks'
    | '/x/docs/protocol-trojan'
    | '/x/docs/protocol-vless'
    | '/x/docs/protocol-vmess'
    | '/x/docs/quick-start'
    | '/x/docs/remote-servers'
    | '/x/docs/routed-outbound'
    | '/x/docs/share-server'
    | '/x/docs/subscribe-files'
    | '/x/docs/system-requirements'
    | '/x/docs/system-settings'
    | '/x/docs/templates'
    | '/x/docs/tool-cloudflare-turnstile'
    | '/x/docs/tool-mmwx-tgbot'
    | '/x/docs/tutorial'
    | '/x/docs/update'
    | '/x/docs/upgrade-from-mmw'
    | '/x/docs/users'
    | '/x/docs/xray-inbounds'
    | '/x/docs/xray-outbounds'
    | '/x/docs/xray-routing'
    | '/x/docs/xray-service'
    | '/x/docs/xray-system-config'
    | '/x/docs'
  id:
    | '__root__'
    | '/'
    | '/change-password'
    | '/changelog'
    | '/custom-rules'
    | '/docs'
    | '/generator'
    | '/login'
    | '/nodes'
    | '/probe'
    | '/rules'
    | '/settings'
    | '/subscribe-files'
    | '/subscription'
    | '/system-settings'
    | '/templates'
    | '/users'
    | '/x'
    | '/docs/about'
    | '/docs/chain-proxy'
    | '/docs/client-setup'
    | '/docs/custom-rules'
    | '/docs/edit-nodes'
    | '/docs/external-subscriptions'
    | '/docs/faq'
    | '/docs/features'
    | '/docs/generator'
    | '/docs/import-subscription'
    | '/docs/install-direct'
    | '/docs/install-docker'
    | '/docs/login'
    | '/docs/node-speedtest'
    | '/docs/nodes'
    | '/docs/probe'
    | '/docs/proxy-providers'
    | '/docs/proxy-providers-advanced'
    | '/docs/quick-start'
    | '/docs/settings'
    | '/docs/subscribe-files'
    | '/docs/subscription-link'
    | '/docs/system-requirements'
    | '/docs/system-settings'
    | '/docs/templates'
    | '/docs/templatesV3'
    | '/docs/traffic-info'
    | '/docs/update'
    | '/docs/users'
    | '/subscribe-files/custom'
    | '/x/docs'
    | '/custom-rules/'
    | '/docs/'
    | '/nodes/'
    | '/subscribe-files/'
    | '/subscription/'
    | '/templates/'
    | '/x/'
    | '/x/docs/about'
    | '/x/docs/certificates'
    | '/x/docs/changelog'
    | '/x/docs/comparison'
    | '/x/docs/custom-rules'
    | '/x/docs/embedded-xray'
    | '/x/docs/faq'
    | '/x/docs/features'
    | '/x/docs/generator'
    | '/x/docs/install-agent'
    | '/x/docs/install-direct'
    | '/x/docs/install-docker'
    | '/x/docs/mcp'
    | '/x/docs/node-ratelimit'
    | '/x/docs/node-speedtest'
    | '/x/docs/nodes'
    | '/x/docs/packages'
    | '/x/docs/protocol-anytls'
    | '/x/docs/protocol-hysteria2'
    | '/x/docs/protocol-matrix'
    | '/x/docs/protocol-shadowsocks'
    | '/x/docs/protocol-trojan'
    | '/x/docs/protocol-vless'
    | '/x/docs/protocol-vmess'
    | '/x/docs/quick-start'
    | '/x/docs/remote-servers'
    | '/x/docs/routed-outbound'
    | '/x/docs/share-server'
    | '/x/docs/subscribe-files'
    | '/x/docs/system-requirements'
    | '/x/docs/system-settings'
    | '/x/docs/templates'
    | '/x/docs/tool-cloudflare-turnstile'
    | '/x/docs/tool-mmwx-tgbot'
    | '/x/docs/tutorial'
    | '/x/docs/update'
    | '/x/docs/upgrade-from-mmw'
    | '/x/docs/users'
    | '/x/docs/xray-inbounds'
    | '/x/docs/xray-outbounds'
    | '/x/docs/xray-routing'
    | '/x/docs/xray-service'
    | '/x/docs/xray-system-config'
    | '/x/docs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChangePasswordRoute: typeof ChangePasswordRoute
  ChangelogRoute: typeof ChangelogRoute
  CustomRulesRoute: typeof CustomRulesRouteWithChildren
  DocsRoute: typeof DocsRouteWithChildren
  GeneratorRoute: typeof GeneratorRoute
  LoginRoute: typeof LoginRoute
  NodesRoute: typeof NodesRouteWithChildren
  ProbeRoute: typeof ProbeRoute
  RulesRoute: typeof RulesRoute
  SettingsRoute: typeof SettingsRoute
  SubscribeFilesRoute: typeof SubscribeFilesRouteWithChildren
  SubscriptionRoute: typeof SubscriptionRouteWithChildren
  SystemSettingsRoute: typeof SystemSettingsRoute
  TemplatesRoute: typeof TemplatesRouteWithChildren
  UsersRoute: typeof UsersRoute
  XRoute: typeof XRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/x': {
      id: '/x'
      path: '/x'
      fullPath: '/x'
      preLoaderRoute: typeof XRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system-settings': {
      id: '/system-settings'
      path: '/system-settings'
      fullPath: '/system-settings'
      preLoaderRoute: typeof SystemSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscription': {
      id: '/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof SubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscribe-files': {
      id: '/subscribe-files'
      path: '/subscribe-files'
      fullPath: '/subscribe-files'
      preLoaderRoute: typeof SubscribeFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/probe': {
      id: '/probe'
      path: '/probe'
      fullPath: '/probe'
      preLoaderRoute: typeof ProbeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nodes': {
      id: '/nodes'
      path: '/nodes'
      fullPath: '/nodes'
      preLoaderRoute: typeof NodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generator': {
      id: '/generator'
      path: '/generator'
      fullPath: '/generator'
      preLoaderRoute: typeof GeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-rules': {
      id: '/custom-rules'
      path: '/custom-rules'
      fullPath: '/custom-rules'
      preLoaderRoute: typeof CustomRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/x/': {
      id: '/x/'
      path: '/'
      fullPath: '/x/'
      preLoaderRoute: typeof XIndexRouteImport
      parentRoute: typeof XRoute
    }
    '/templates/': {
      id: '/templates/'
      path: '/'
      fullPath: '/templates/'
      preLoaderRoute: typeof TemplatesIndexRouteImport
      parentRoute: typeof TemplatesRoute
    }
    '/subscription/': {
      id: '/subscription/'
      path: '/'
      fullPath: '/subscription/'
      preLoaderRoute: typeof SubscriptionIndexRouteImport
      parentRoute: typeof SubscriptionRoute
    }
    '/subscribe-files/': {
      id: '/subscribe-files/'
      path: '/'
      fullPath: '/subscribe-files/'
      preLoaderRoute: typeof SubscribeFilesIndexRouteImport
      parentRoute: typeof SubscribeFilesRoute
    }
    '/nodes/': {
      id: '/nodes/'
      path: '/'
      fullPath: '/nodes/'
      preLoaderRoute: typeof NodesIndexRouteImport
      parentRoute: typeof NodesRoute
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/custom-rules/': {
      id: '/custom-rules/'
      path: '/'
      fullPath: '/custom-rules/'
      preLoaderRoute: typeof CustomRulesIndexRouteImport
      parentRoute: typeof CustomRulesRoute
    }
    '/x/docs': {
      id: '/x/docs'
      path: '/docs'
      fullPath: '/x/docs'
      preLoaderRoute: typeof XDocsRouteImport
      parentRoute: typeof XRoute
    }
    '/subscribe-files/custom': {
      id: '/subscribe-files/custom'
      path: '/custom'
      fullPath: '/subscribe-files/custom'
      preLoaderRoute: typeof SubscribeFilesCustomRouteImport
      parentRoute: typeof SubscribeFilesRoute
    }
    '/docs/users': {
      id: '/docs/users'
      path: '/users'
      fullPath: '/docs/users'
      preLoaderRoute: typeof DocsUsersRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/update': {
      id: '/docs/update'
      path: '/update'
      fullPath: '/docs/update'
      preLoaderRoute: typeof DocsUpdateRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/traffic-info': {
      id: '/docs/traffic-info'
      path: '/traffic-info'
      fullPath: '/docs/traffic-info'
      preLoaderRoute: typeof DocsTrafficInfoRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/templatesV3': {
      id: '/docs/templatesV3'
      path: '/templatesV3'
      fullPath: '/docs/templatesV3'
      preLoaderRoute: typeof DocsTemplatesV3RouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/templates': {
      id: '/docs/templates'
      path: '/templates'
      fullPath: '/docs/templates'
      preLoaderRoute: typeof DocsTemplatesRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/system-settings': {
      id: '/docs/system-settings'
      path: '/system-settings'
      fullPath: '/docs/system-settings'
      preLoaderRoute: typeof DocsSystemSettingsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/system-requirements': {
      id: '/docs/system-requirements'
      path: '/system-requirements'
      fullPath: '/docs/system-requirements'
      preLoaderRoute: typeof DocsSystemRequirementsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/subscription-link': {
      id: '/docs/subscription-link'
      path: '/subscription-link'
      fullPath: '/docs/subscription-link'
      preLoaderRoute: typeof DocsSubscriptionLinkRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/subscribe-files': {
      id: '/docs/subscribe-files'
      path: '/subscribe-files'
      fullPath: '/docs/subscribe-files'
      preLoaderRoute: typeof DocsSubscribeFilesRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/settings': {
      id: '/docs/settings'
      path: '/settings'
      fullPath: '/docs/settings'
      preLoaderRoute: typeof DocsSettingsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/quick-start': {
      id: '/docs/quick-start'
      path: '/quick-start'
      fullPath: '/docs/quick-start'
      preLoaderRoute: typeof DocsQuickStartRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/proxy-providers-advanced': {
      id: '/docs/proxy-providers-advanced'
      path: '/proxy-providers-advanced'
      fullPath: '/docs/proxy-providers-advanced'
      preLoaderRoute: typeof DocsProxyProvidersAdvancedRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/proxy-providers': {
      id: '/docs/proxy-providers'
      path: '/proxy-providers'
      fullPath: '/docs/proxy-providers'
      preLoaderRoute: typeof DocsProxyProvidersRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/probe': {
      id: '/docs/probe'
      path: '/probe'
      fullPath: '/docs/probe'
      preLoaderRoute: typeof DocsProbeRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/nodes': {
      id: '/docs/nodes'
      path: '/nodes'
      fullPath: '/docs/nodes'
      preLoaderRoute: typeof DocsNodesRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/node-speedtest': {
      id: '/docs/node-speedtest'
      path: '/node-speedtest'
      fullPath: '/docs/node-speedtest'
      preLoaderRoute: typeof DocsNodeSpeedtestRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/login': {
      id: '/docs/login'
      path: '/login'
      fullPath: '/docs/login'
      preLoaderRoute: typeof DocsLoginRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/install-docker': {
      id: '/docs/install-docker'
      path: '/install-docker'
      fullPath: '/docs/install-docker'
      preLoaderRoute: typeof DocsInstallDockerRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/install-direct': {
      id: '/docs/install-direct'
      path: '/install-direct'
      fullPath: '/docs/install-direct'
      preLoaderRoute: typeof DocsInstallDirectRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/import-subscription': {
      id: '/docs/import-subscription'
      path: '/import-subscription'
      fullPath: '/docs/import-subscription'
      preLoaderRoute: typeof DocsImportSubscriptionRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/generator': {
      id: '/docs/generator'
      path: '/generator'
      fullPath: '/docs/generator'
      preLoaderRoute: typeof DocsGeneratorRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/features': {
      id: '/docs/features'
      path: '/features'
      fullPath: '/docs/features'
      preLoaderRoute: typeof DocsFeaturesRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/faq': {
      id: '/docs/faq'
      path: '/faq'
      fullPath: '/docs/faq'
      preLoaderRoute: typeof DocsFaqRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/external-subscriptions': {
      id: '/docs/external-subscriptions'
      path: '/external-subscriptions'
      fullPath: '/docs/external-subscriptions'
      preLoaderRoute: typeof DocsExternalSubscriptionsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/edit-nodes': {
      id: '/docs/edit-nodes'
      path: '/edit-nodes'
      fullPath: '/docs/edit-nodes'
      preLoaderRoute: typeof DocsEditNodesRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/custom-rules': {
      id: '/docs/custom-rules'
      path: '/custom-rules'
      fullPath: '/docs/custom-rules'
      preLoaderRoute: typeof DocsCustomRulesRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/client-setup': {
      id: '/docs/client-setup'
      path: '/client-setup'
      fullPath: '/docs/client-setup'
      preLoaderRoute: typeof DocsClientSetupRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/chain-proxy': {
      id: '/docs/chain-proxy'
      path: '/chain-proxy'
      fullPath: '/docs/chain-proxy'
      preLoaderRoute: typeof DocsChainProxyRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/about': {
      id: '/docs/about'
      path: '/about'
      fullPath: '/docs/about'
      preLoaderRoute: typeof DocsAboutRouteImport
      parentRoute: typeof DocsRoute
    }
    '/x/docs/': {
      id: '/x/docs/'
      path: '/'
      fullPath: '/x/docs/'
      preLoaderRoute: typeof XDocsIndexRouteImport
      parentRoute: typeof XDocsRoute
    }
    '/x/docs/xray-system-config': {
      id: '/x/docs/xray-system-config'
      path: '/xray-system-config'
      fullPath: '/x/docs/xray-system-config'
      preLoaderRoute: typeof XDocsXraySystemConfigRouteImport
      parentRoute: typeof XDocsRoute
    }
    '/x/docs/xray-service': {
      id: '/x/docs/xray-service'
      path: '/xray-service'
      fullPath: '/x/docs/xray-service'
      preLoaderRoute: typeof XDocsXrayServiceRouteImport
      parentRoute: typeof XDocsRoute
    }
    '/x/docs/xray-routing': {
      id: '/x/docs/xray-routing'
      path: '/xray-routing'
      fullPath: '/x/docs/xray-routing'
      preLoaderRoute: typeof XDocsXrayRoutingRouteImport
      parentRoute: typeof XDocsRoute
    }
    '/x/docs/xray-outbounds': {
      id: '/x/docs/xray-outbounds'
      path: '/xray-outbounds'
      fullPath: '/x/docs/xray-outbounds'
      preLoaderRoute: typeof XDocsXrayOutboundsRouteImport
      parentRoute: typeof XDocsRoute
    }
    '/x/docs/xray-inbounds': {
      id: '/x/docs/xray-inbounds'
      path: '/xray-inbounds'
      fullPath: '/x/docs/xray-inbounds'
      preLoaderRoute: typeof XDocsXrayInboundsRouteImport
      parentRoute: typeof XDocsRoute
    }
    '/x/docs/users': {
      id: '/x/docs/users'
      path: '/users'
      fullPath: '/x/docs/users'
      preLoaderRoute: typeof XDocsUsersRouteImport
      parentRoute: typeof XDocsRoute
    }
    '/x/docs/upgrade-from-mmw': {
      id: '/x/docs/upgrade-from-mmw'
      path: '/upgrade-from-mmw'
      fullPath: '/x/docs/upgrade-from-mmw'
      preLoaderRoute: typeof XDocsUpgradeFromMmwRouteImport
      parentRoute: typeof XDocsRoute
    }
    '/x/docs/update': {
      id: '/x/docs/update'
      path: '/update'
      fullPath: '/x/docs/update'
      preLoaderRoute: typeof XDocsUpdateRouteImport
      parentRoute: typeof XDocsRoute
    }
    '/x/docs/tutorial': {
      id: '/x/docs/tutorial'
      path: '/tutorial'
      fullPath: '/x/docs/tutorial'
      preLoaderRoute: typeof XDocsTutorialRouteImport
      parentRoute: typeof XDocsRoute
    }
    '/x/docs/tool-mmwx-tgbot': {
      id: '/x/docs/tool-mmwx-tgbot'
      path: '/tool-mmwx-tgbot'
      fullPath: '/x/docs/tool-mmwx-tgbot'
      preLoaderRoute: typeof XDocsToolMmwxTgbotRouteImport
      parentRoute: typeof XDocsRoute
    }
    '/x/docs/tool-cloudflare-turnstile': {
      id: '/x/docs/tool-cloudflare-turnstile'
      path: '/tool-cloudflare-turnstile'
      fullPath: '/x/docs/tool-cloudflare-turnstile'
      preLoaderRoute: typeof XDocsToolCloudflareTurnstileRouteImport
      parentRoute: typeof XDocsRoute
    }
    '/x/docs/templates': {
      id: '/x/docs/templates'
      path: '/templates'
      fullPath: '/x/docs/templates'
      preLoaderRoute: typeof XDocsTemplatesRouteImport
      parentRoute: typeof XDocsRoute
    }
    '/x/docs/system-settings': {
      id: '/x/docs/system-settings'
      path: '/system-settings'
      fullPath: '/x/docs/system-settings'
      preLoaderRoute: typeof XDocsSystemSettingsRouteImport
      parentRoute: typeof XDocsRoute
    }
    '/x/docs/system-requirements': {
      id: '/x/docs/system-requirements'
      path: '/system-requirements'
      fullPath: '/x/docs/system-requirements'
      preLoaderRoute: typeof XDocsSystemRequirementsRouteImport
      parentRoute: typeof XDocsRoute
    }
    '/x/docs/subscribe-files': {
      id: '/x/docs/subscribe-files'
      path: '/subscribe-files'
      fullPath: '/x/docs/subscribe-files'
      preLoaderRoute: typeof XDocsSubscribeFilesRouteImport
      parentRoute: typeof XDocsRoute
    }
    '/x/docs/share-server': {
      id: '/x/docs/share-server'
      path: '/share-server'
      fullPath: '/x/docs/share-server'
      preLoaderRoute: typeof XDocsShareServerRouteImport
      parentRoute: typeof XDocsRoute
    }
    '/x/docs/routed-outbound': {
      id: '/x/docs/routed-outbound'
      path: '/routed-outbound'
      fullPath: '/x/docs/routed-outbound'
      preLoaderRoute: typeof XDocsRoutedOutboundRouteImport
      parentRoute: typeof XDocsRoute
    }
    '/x/docs/remote-servers': {
      id: '/x/docs/remote-servers'
      path: '/remote-servers'
      fullPath: '/x/docs/remote-servers'
      preLoaderRoute: typeof XDocsRemoteServersRouteImport
      parentRoute: typeof XDocsRoute
    }
    '/x/docs/quick-start': {
      id: '/x/docs/quick-start'
      path: '/quick-start'
      fullPath: '/x/docs/quick-start'
      preLoaderRoute: typeof XDocsQuickStartRouteImport
      parentRoute: typeof XDocsRoute
    }
    '/x/docs/protocol-vmess': {
      id: '/x/docs/protocol-vmess'
      path: '/protocol-vmess'
      fullPath: '/x/docs/protocol-vmess'
      preLoaderRoute: typeof XDocsProtocolVmessRouteImport
      parentRoute: typeof XDocsRoute
    }
    '/x/docs/protocol-vless': {
      id: '/x/docs/protocol-vless'
      path: '/protocol-vless'
      fullPath: '/x/docs/protocol-vless'
      preLoaderRoute: typeof XDocsProtocolVlessRouteImport
      parentRoute: typeof XDocsRoute
    }
    '/x/docs/protocol-trojan': {
      id: '/x/docs/protocol-trojan'
      path: '/protocol-trojan'
      fullPath: '/x/docs/protocol-trojan'
      preLoaderRoute: typeof XDocsProtocolTrojanRouteImport
      parentRoute: typeof XDocsRoute
    }
    '/x/docs/protocol-shadowsocks': {
      id: '/x/docs/protocol-shadowsocks'
      path: '/protocol-shadowsocks'
      fullPath: '/x/docs/protocol-shadowsocks'
      preLoaderRoute: typeof XDocsProtocolShadowsocksRouteImport
      parentRoute: typeof XDocsRoute
    }
    '/x/docs/protocol-matrix': {
      id: '/x/docs/protocol-matrix'
      path: '/protocol-matrix'
      fullPath: '/x/docs/protocol-matrix'
      preLoaderRoute: typeof XDocsProtocolMatrixRouteImport
      parentRoute: typeof XDocsRoute
    }
    '/x/docs/protocol-hysteria2': {
      id: '/x/docs/protocol-hysteria2'
      path: '/protocol-hysteria2'
      fullPath: '/x/docs/protocol-hysteria2'
      preLoaderRoute: typeof XDocsProtocolHysteria2RouteImport
      parentRoute: typeof XDocsRoute
    }
    '/x/docs/protocol-anytls': {
      id: '/x/docs/protocol-anytls'
      path: '/protocol-anytls'
      fullPath: '/x/docs/protocol-anytls'
      preLoaderRoute: typeof XDocsProtocolAnytlsRouteImport
      parentRoute: typeof XDocsRoute
    }
    '/x/docs/packages': {
      id: '/x/docs/packages'
      path: '/packages'
      fullPath: '/x/docs/packages'
      preLoaderRoute: typeof XDocsPackagesRouteImport
      parentRoute: typeof XDocsRoute
    }
    '/x/docs/nodes': {
      id: '/x/docs/nodes'
      path: '/nodes'
      fullPath: '/x/docs/nodes'
      preLoaderRoute: typeof XDocsNodesRouteImport
      parentRoute: typeof XDocsRoute
    }
    '/x/docs/node-speedtest': {
      id: '/x/docs/node-speedtest'
      path: '/node-speedtest'
      fullPath: '/x/docs/node-speedtest'
      preLoaderRoute: typeof XDocsNodeSpeedtestRouteImport
      parentRoute: typeof XDocsRoute
    }
    '/x/docs/node-ratelimit': {
      id: '/x/docs/node-ratelimit'
      path: '/node-ratelimit'
      fullPath: '/x/docs/node-ratelimit'
      preLoaderRoute: typeof XDocsNodeRatelimitRouteImport
      parentRoute: typeof XDocsRoute
    }
    '/x/docs/mcp': {
      id: '/x/docs/mcp'
      path: '/mcp'
      fullPath: '/x/docs/mcp'
      preLoaderRoute: typeof XDocsMcpRouteImport
      parentRoute: typeof XDocsRoute
    }
    '/x/docs/install-docker': {
      id: '/x/docs/install-docker'
      path: '/install-docker'
      fullPath: '/x/docs/install-docker'
      preLoaderRoute: typeof XDocsInstallDockerRouteImport
      parentRoute: typeof XDocsRoute
    }
    '/x/docs/install-direct': {
      id: '/x/docs/install-direct'
      path: '/install-direct'
      fullPath: '/x/docs/install-direct'
      preLoaderRoute: typeof XDocsInstallDirectRouteImport
      parentRoute: typeof XDocsRoute
    }
    '/x/docs/install-agent': {
      id: '/x/docs/install-agent'
      path: '/install-agent'
      fullPath: '/x/docs/install-agent'
      preLoaderRoute: typeof XDocsInstallAgentRouteImport
      parentRoute: typeof XDocsRoute
    }
    '/x/docs/generator': {
      id: '/x/docs/generator'
      path: '/generator'
      fullPath: '/x/docs/generator'
      preLoaderRoute: typeof XDocsGeneratorRouteImport
      parentRoute: typeof XDocsRoute
    }
    '/x/docs/features': {
      id: '/x/docs/features'
      path: '/features'
      fullPath: '/x/docs/features'
      preLoaderRoute: typeof XDocsFeaturesRouteImport
      parentRoute: typeof XDocsRoute
    }
    '/x/docs/faq': {
      id: '/x/docs/faq'
      path: '/faq'
      fullPath: '/x/docs/faq'
      preLoaderRoute: typeof XDocsFaqRouteImport
      parentRoute: typeof XDocsRoute
    }
    '/x/docs/embedded-xray': {
      id: '/x/docs/embedded-xray'
      path: '/embedded-xray'
      fullPath: '/x/docs/embedded-xray'
      preLoaderRoute: typeof XDocsEmbeddedXrayRouteImport
      parentRoute: typeof XDocsRoute
    }
    '/x/docs/custom-rules': {
      id: '/x/docs/custom-rules'
      path: '/custom-rules'
      fullPath: '/x/docs/custom-rules'
      preLoaderRoute: typeof XDocsCustomRulesRouteImport
      parentRoute: typeof XDocsRoute
    }
    '/x/docs/comparison': {
      id: '/x/docs/comparison'
      path: '/comparison'
      fullPath: '/x/docs/comparison'
      preLoaderRoute: typeof XDocsComparisonRouteImport
      parentRoute: typeof XDocsRoute
    }
    '/x/docs/changelog': {
      id: '/x/docs/changelog'
      path: '/changelog'
      fullPath: '/x/docs/changelog'
      preLoaderRoute: typeof XDocsChangelogRouteImport
      parentRoute: typeof XDocsRoute
    }
    '/x/docs/certificates': {
      id: '/x/docs/certificates'
      path: '/certificates'
      fullPath: '/x/docs/certificates'
      preLoaderRoute: typeof XDocsCertificatesRouteImport
      parentRoute: typeof XDocsRoute
    }
    '/x/docs/about': {
      id: '/x/docs/about'
      path: '/about'
      fullPath: '/x/docs/about'
      preLoaderRoute: typeof XDocsAboutRouteImport
      parentRoute: typeof XDocsRoute
    }
  }
}

interface CustomRulesRouteChildren {
  CustomRulesIndexRoute: typeof CustomRulesIndexRoute
}

const CustomRulesRouteChildren: CustomRulesRouteChildren = {
  CustomRulesIndexRoute: CustomRulesIndexRoute,
}

const CustomRulesRouteWithChildren = CustomRulesRoute._addFileChildren(
  CustomRulesRouteChildren,
)

interface DocsRouteChildren {
  DocsAboutRoute: typeof DocsAboutRoute
  DocsChainProxyRoute: typeof DocsChainProxyRoute
  DocsClientSetupRoute: typeof DocsClientSetupRoute
  DocsCustomRulesRoute: typeof DocsCustomRulesRoute
  DocsEditNodesRoute: typeof DocsEditNodesRoute
  DocsExternalSubscriptionsRoute: typeof DocsExternalSubscriptionsRoute
  DocsFaqRoute: typeof DocsFaqRoute
  DocsFeaturesRoute: typeof DocsFeaturesRoute
  DocsGeneratorRoute: typeof DocsGeneratorRoute
  DocsImportSubscriptionRoute: typeof DocsImportSubscriptionRoute
  DocsInstallDirectRoute: typeof DocsInstallDirectRoute
  DocsInstallDockerRoute: typeof DocsInstallDockerRoute
  DocsLoginRoute: typeof DocsLoginRoute
  DocsNodeSpeedtestRoute: typeof DocsNodeSpeedtestRoute
  DocsNodesRoute: typeof DocsNodesRoute
  DocsProbeRoute: typeof DocsProbeRoute
  DocsProxyProvidersRoute: typeof DocsProxyProvidersRoute
  DocsProxyProvidersAdvancedRoute: typeof DocsProxyProvidersAdvancedRoute
  DocsQuickStartRoute: typeof DocsQuickStartRoute
  DocsSettingsRoute: typeof DocsSettingsRoute
  DocsSubscribeFilesRoute: typeof DocsSubscribeFilesRoute
  DocsSubscriptionLinkRoute: typeof DocsSubscriptionLinkRoute
  DocsSystemRequirementsRoute: typeof DocsSystemRequirementsRoute
  DocsSystemSettingsRoute: typeof DocsSystemSettingsRoute
  DocsTemplatesRoute: typeof DocsTemplatesRoute
  DocsTemplatesV3Route: typeof DocsTemplatesV3Route
  DocsTrafficInfoRoute: typeof DocsTrafficInfoRoute
  DocsUpdateRoute: typeof DocsUpdateRoute
  DocsUsersRoute: typeof DocsUsersRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsAboutRoute: DocsAboutRoute,
  DocsChainProxyRoute: DocsChainProxyRoute,
  DocsClientSetupRoute: DocsClientSetupRoute,
  DocsCustomRulesRoute: DocsCustomRulesRoute,
  DocsEditNodesRoute: DocsEditNodesRoute,
  DocsExternalSubscriptionsRoute: DocsExternalSubscriptionsRoute,
  DocsFaqRoute: DocsFaqRoute,
  DocsFeaturesRoute: DocsFeaturesRoute,
  DocsGeneratorRoute: DocsGeneratorRoute,
  DocsImportSubscriptionRoute: DocsImportSubscriptionRoute,
  DocsInstallDirectRoute: DocsInstallDirectRoute,
  DocsInstallDockerRoute: DocsInstallDockerRoute,
  DocsLoginRoute: DocsLoginRoute,
  DocsNodeSpeedtestRoute: DocsNodeSpeedtestRoute,
  DocsNodesRoute: DocsNodesRoute,
  DocsProbeRoute: DocsProbeRoute,
  DocsProxyProvidersRoute: DocsProxyProvidersRoute,
  DocsProxyProvidersAdvancedRoute: DocsProxyProvidersAdvancedRoute,
  DocsQuickStartRoute: DocsQuickStartRoute,
  DocsSettingsRoute: DocsSettingsRoute,
  DocsSubscribeFilesRoute: DocsSubscribeFilesRoute,
  DocsSubscriptionLinkRoute: DocsSubscriptionLinkRoute,
  DocsSystemRequirementsRoute: DocsSystemRequirementsRoute,
  DocsSystemSettingsRoute: DocsSystemSettingsRoute,
  DocsTemplatesRoute: DocsTemplatesRoute,
  DocsTemplatesV3Route: DocsTemplatesV3Route,
  DocsTrafficInfoRoute: DocsTrafficInfoRoute,
  DocsUpdateRoute: DocsUpdateRoute,
  DocsUsersRoute: DocsUsersRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

interface NodesRouteChildren {
  NodesIndexRoute: typeof NodesIndexRoute
}

const NodesRouteChildren: NodesRouteChildren = {
  NodesIndexRoute: NodesIndexRoute,
}

const NodesRouteWithChildren = NodesRoute._addFileChildren(NodesRouteChildren)

interface SubscribeFilesRouteChildren {
  SubscribeFilesCustomRoute: typeof SubscribeFilesCustomRoute
  SubscribeFilesIndexRoute: typeof SubscribeFilesIndexRoute
}

const SubscribeFilesRouteChildren: SubscribeFilesRouteChildren = {
  SubscribeFilesCustomRoute: SubscribeFilesCustomRoute,
  SubscribeFilesIndexRoute: SubscribeFilesIndexRoute,
}

const SubscribeFilesRouteWithChildren = SubscribeFilesRoute._addFileChildren(
  SubscribeFilesRouteChildren,
)

interface SubscriptionRouteChildren {
  SubscriptionIndexRoute: typeof SubscriptionIndexRoute
}

const SubscriptionRouteChildren: SubscriptionRouteChildren = {
  SubscriptionIndexRoute: SubscriptionIndexRoute,
}

const SubscriptionRouteWithChildren = SubscriptionRoute._addFileChildren(
  SubscriptionRouteChildren,
)

interface TemplatesRouteChildren {
  TemplatesIndexRoute: typeof TemplatesIndexRoute
}

const TemplatesRouteChildren: TemplatesRouteChildren = {
  TemplatesIndexRoute: TemplatesIndexRoute,
}

const TemplatesRouteWithChildren = TemplatesRoute._addFileChildren(
  TemplatesRouteChildren,
)

interface XDocsRouteChildren {
  XDocsAboutRoute: typeof XDocsAboutRoute
  XDocsCertificatesRoute: typeof XDocsCertificatesRoute
  XDocsChangelogRoute: typeof XDocsChangelogRoute
  XDocsComparisonRoute: typeof XDocsComparisonRoute
  XDocsCustomRulesRoute: typeof XDocsCustomRulesRoute
  XDocsEmbeddedXrayRoute: typeof XDocsEmbeddedXrayRoute
  XDocsFaqRoute: typeof XDocsFaqRoute
  XDocsFeaturesRoute: typeof XDocsFeaturesRoute
  XDocsGeneratorRoute: typeof XDocsGeneratorRoute
  XDocsInstallAgentRoute: typeof XDocsInstallAgentRoute
  XDocsInstallDirectRoute: typeof XDocsInstallDirectRoute
  XDocsInstallDockerRoute: typeof XDocsInstallDockerRoute
  XDocsMcpRoute: typeof XDocsMcpRoute
  XDocsNodeRatelimitRoute: typeof XDocsNodeRatelimitRoute
  XDocsNodeSpeedtestRoute: typeof XDocsNodeSpeedtestRoute
  XDocsNodesRoute: typeof XDocsNodesRoute
  XDocsPackagesRoute: typeof XDocsPackagesRoute
  XDocsProtocolAnytlsRoute: typeof XDocsProtocolAnytlsRoute
  XDocsProtocolHysteria2Route: typeof XDocsProtocolHysteria2Route
  XDocsProtocolMatrixRoute: typeof XDocsProtocolMatrixRoute
  XDocsProtocolShadowsocksRoute: typeof XDocsProtocolShadowsocksRoute
  XDocsProtocolTrojanRoute: typeof XDocsProtocolTrojanRoute
  XDocsProtocolVlessRoute: typeof XDocsProtocolVlessRoute
  XDocsProtocolVmessRoute: typeof XDocsProtocolVmessRoute
  XDocsQuickStartRoute: typeof XDocsQuickStartRoute
  XDocsRemoteServersRoute: typeof XDocsRemoteServersRoute
  XDocsRoutedOutboundRoute: typeof XDocsRoutedOutboundRoute
  XDocsShareServerRoute: typeof XDocsShareServerRoute
  XDocsSubscribeFilesRoute: typeof XDocsSubscribeFilesRoute
  XDocsSystemRequirementsRoute: typeof XDocsSystemRequirementsRoute
  XDocsSystemSettingsRoute: typeof XDocsSystemSettingsRoute
  XDocsTemplatesRoute: typeof XDocsTemplatesRoute
  XDocsToolCloudflareTurnstileRoute: typeof XDocsToolCloudflareTurnstileRoute
  XDocsToolMmwxTgbotRoute: typeof XDocsToolMmwxTgbotRoute
  XDocsTutorialRoute: typeof XDocsTutorialRoute
  XDocsUpdateRoute: typeof XDocsUpdateRoute
  XDocsUpgradeFromMmwRoute: typeof XDocsUpgradeFromMmwRoute
  XDocsUsersRoute: typeof XDocsUsersRoute
  XDocsXrayInboundsRoute: typeof XDocsXrayInboundsRoute
  XDocsXrayOutboundsRoute: typeof XDocsXrayOutboundsRoute
  XDocsXrayRoutingRoute: typeof XDocsXrayRoutingRoute
  XDocsXrayServiceRoute: typeof XDocsXrayServiceRoute
  XDocsXraySystemConfigRoute: typeof XDocsXraySystemConfigRoute
  XDocsIndexRoute: typeof XDocsIndexRoute
}

const XDocsRouteChildren: XDocsRouteChildren = {
  XDocsAboutRoute: XDocsAboutRoute,
  XDocsCertificatesRoute: XDocsCertificatesRoute,
  XDocsChangelogRoute: XDocsChangelogRoute,
  XDocsComparisonRoute: XDocsComparisonRoute,
  XDocsCustomRulesRoute: XDocsCustomRulesRoute,
  XDocsEmbeddedXrayRoute: XDocsEmbeddedXrayRoute,
  XDocsFaqRoute: XDocsFaqRoute,
  XDocsFeaturesRoute: XDocsFeaturesRoute,
  XDocsGeneratorRoute: XDocsGeneratorRoute,
  XDocsInstallAgentRoute: XDocsInstallAgentRoute,
  XDocsInstallDirectRoute: XDocsInstallDirectRoute,
  XDocsInstallDockerRoute: XDocsInstallDockerRoute,
  XDocsMcpRoute: XDocsMcpRoute,
  XDocsNodeRatelimitRoute: XDocsNodeRatelimitRoute,
  XDocsNodeSpeedtestRoute: XDocsNodeSpeedtestRoute,
  XDocsNodesRoute: XDocsNodesRoute,
  XDocsPackagesRoute: XDocsPackagesRoute,
  XDocsProtocolAnytlsRoute: XDocsProtocolAnytlsRoute,
  XDocsProtocolHysteria2Route: XDocsProtocolHysteria2Route,
  XDocsProtocolMatrixRoute: XDocsProtocolMatrixRoute,
  XDocsProtocolShadowsocksRoute: XDocsProtocolShadowsocksRoute,
  XDocsProtocolTrojanRoute: XDocsProtocolTrojanRoute,
  XDocsProtocolVlessRoute: XDocsProtocolVlessRoute,
  XDocsProtocolVmessRoute: XDocsProtocolVmessRoute,
  XDocsQuickStartRoute: XDocsQuickStartRoute,
  XDocsRemoteServersRoute: XDocsRemoteServersRoute,
  XDocsRoutedOutboundRoute: XDocsRoutedOutboundRoute,
  XDocsShareServerRoute: XDocsShareServerRoute,
  XDocsSubscribeFilesRoute: XDocsSubscribeFilesRoute,
  XDocsSystemRequirementsRoute: XDocsSystemRequirementsRoute,
  XDocsSystemSettingsRoute: XDocsSystemSettingsRoute,
  XDocsTemplatesRoute: XDocsTemplatesRoute,
  XDocsToolCloudflareTurnstileRoute: XDocsToolCloudflareTurnstileRoute,
  XDocsToolMmwxTgbotRoute: XDocsToolMmwxTgbotRoute,
  XDocsTutorialRoute: XDocsTutorialRoute,
  XDocsUpdateRoute: XDocsUpdateRoute,
  XDocsUpgradeFromMmwRoute: XDocsUpgradeFromMmwRoute,
  XDocsUsersRoute: XDocsUsersRoute,
  XDocsXrayInboundsRoute: XDocsXrayInboundsRoute,
  XDocsXrayOutboundsRoute: XDocsXrayOutboundsRoute,
  XDocsXrayRoutingRoute: XDocsXrayRoutingRoute,
  XDocsXrayServiceRoute: XDocsXrayServiceRoute,
  XDocsXraySystemConfigRoute: XDocsXraySystemConfigRoute,
  XDocsIndexRoute: XDocsIndexRoute,
}

const XDocsRouteWithChildren = XDocsRoute._addFileChildren(XDocsRouteChildren)

interface XRouteChildren {
  XDocsRoute: typeof XDocsRouteWithChildren
  XIndexRoute: typeof XIndexRoute
}

const XRouteChildren: XRouteChildren = {
  XDocsRoute: XDocsRouteWithChildren,
  XIndexRoute: XIndexRoute,
}

const XRouteWithChildren = XRoute._addFileChildren(XRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChangePasswordRoute: ChangePasswordRoute,
  ChangelogRoute: ChangelogRoute,
  CustomRulesRoute: CustomRulesRouteWithChildren,
  DocsRoute: DocsRouteWithChildren,
  GeneratorRoute: GeneratorRoute,
  LoginRoute: LoginRoute,
  NodesRoute: NodesRouteWithChildren,
  ProbeRoute: ProbeRoute,
  RulesRoute: RulesRoute,
  SettingsRoute: SettingsRoute,
  SubscribeFilesRoute: SubscribeFilesRouteWithChildren,
  SubscriptionRoute: SubscriptionRouteWithChildren,
  SystemSettingsRoute: SystemSettingsRoute,
  TemplatesRoute: TemplatesRouteWithChildren,
  UsersRoute: UsersRoute,
  XRoute: XRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
